[package]
name = "VellumEngine"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "0.20"
winit = { version = "0.30", features = ["x11", "wayland"] } # Enable Linux backends
glam = "0.27"
pollster = "0.3"